apiVersion: v1
kind: Secret
metadata:
  name: ai-canary-deployment-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/nolet7/ai-canary-deployment.git
  insecure: "true"

